baseURL = "https://marcopizzolato.com/"
languageCode = "en-us"
title = "Marco Pizzolato Portfolio"
theme = "mediumish-gohugo-theme"
summaryLength = 25
DefaultContentLanguage = "en"
copyright = "Marco Pizzolato - All rights reserved"
enableEmoji = true
publishDir = "public_web"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$","\\.knit\\.md$", "\\.utf8\\.md$"]
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-132680808-1"

[permalinks]
    post = "/:year/:month/:day/:slug/"

# This refers to Site.Params
[params]
  logo = "/images/portfolio-02.png"
  logo2 = "/images/rocket_01.png"
  description ="This is the porfolio of Marco Pizzolato" #description of the website for the search engines
  #mailchimp = "you can provide a mailchimp-link here"

[params.author] # Line with the author face-mane
  name = "Marco Pizzolato"
  thumbnail = "/images/marco_rea2.jpg"
  description = "Creator of this blog."
  
[params.index]
  picture = "./images/marcopizzo.jpg"
  title = "Marco Pizzolato"
  subtitle = "GIS Expert & Data Explorer"
  mdtext = '''
\
<b>Welcome to my personal website!</b>  
  
This space is a collection of some of the works I have completed so far, from my time in South Sudan responding to the on-going crisis, to my Master in GIS at Edinburgh. You will also find other data explorations mainly with R.   
     
     
<b>A little about me...</b>
  
Dynamic and energetic I am very passionate about the projects I get involved in. I am always looking for new projects to embark on which will challenge my brain bringing out my inventiveness, creativity and imagination to find the best solution.   
Strongly believing that <i>“Together we stand, alone we fall”</i> I always collaborate in a profitable way with my team members, often building over time strong friendships.  
  
Happy exploring and get in touch if you want to know more!    
</br>
   
<b><a href="http://www.marcopizzolato.com">Explore!</a></b>
'''
  alertbar = false

#TODO

# [params.social]
 # github = "Marcopizzo87"
#   linkedin = "pizzolatomarco"
#   pdf = "file/d/16nn7L30nMfCIKSLkRq1Sbh7QR76H-Frk/view?usp=sharing"
#   mail = "contact@marcopizzolato.com"
  # xing = "<username>"
  # medium = "<username>"

[params.social]
  github = "<username>"
  linkedin = "<username>"
  xing = "<username>"
  medium = "<username>"
  twitter = "<username>"
  instagram = "<username>"

## Main Menu
[[menu.main]]
    name = "Projects" # This is the name in the menu
    weight = 100
    identifier = "projects"
    url = "/" #Done - replacing parts in the index page
    
[[menu.main]]
    name = "About Me"
    identifier = "about_bio"
    weight = 300
    url = "/about/bio"
    
[[menu.main]]
    name = "curriculum"
    identifier = "curriculum_vitae"
    weight = 200
    url = "/curriculum/vitae"

[[menu.main]]
    name = "extra"
    identifier = "extra"
    weight = 400
    url = "/static"